# Generated by Django 5.1.7 on 2025-03-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plant_images/')),
                ('plant_name', models.CharField(max_length=100)),
                ('sunlight_hours', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=20)),
                ('when_planted', models.IntegerField()),
                ('watering_frequency', models.CharField(max_length=50)),
                ('additional_comments', models.TextField(blank=True)),
                ('health_status', models.CharField(blank=True, max_length=20, null=True)),
                ('possible_cause', models.TextField(blank=True, null=True)),
                ('treatment_recommendation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
