# Generated by Django 5.1.7 on 2025-03-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdiagnosis',
            name='when_planted',
        ),
    ]
