# Generated by Django 5.1.7 on 2025-03-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_remove_plantdiagnosis_health_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantdiagnosis',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='plantdiagnosis',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
