# Generated by Django 5.1.7 on 2025-03-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_plantdiagnosis_image_name_plantdiagnosis_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdiagnosis',
            name='image_name',
        ),
    ]
