# Generated by Django 5.1.7 on 2025-03-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0005_remove_plantdiagnosis_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
