# Generated by Django 5.1.7 on 2025-03-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_alter_plantdiagnosis_additional_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantdiagnosis',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='plantdiagnosis',
            name='sunlight_hours',
        ),
        migrations.AddField(
            model_name='plantdiagnosis',
            name='sunlight_info',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
